#!/usr/bin/env node

let puppeteer = require('puppeteer')
let fs = require('fs')

async function download(url, cookies) {
    let browser = await puppeteer.launch()
    let page = await browser.newPage()

    await page.emulateMediaType('screen')
    await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36')

    await page.setRequestInterception(true)
    page.on('request', req => {
        let headers = Object.assign({}, req.headers())
        if (cookies) headers.cookie = cookies

        // ignore all except html
        if (req.resourceType() === 'document') {
            req.continue({headers})
        } else {
            req.abort()
        }
    })

    try {
        await page.goto(url, { waitUntil: 'networkidle2' })
        console.log(await page.content())
    } catch(e) {
        err('Error:', e.message)
    }
    await browser.close()
}

function err(...msg) { console.error(...msg); process.exit(1) }

let url = process.argv[2]
if (!url) err('Usage: puppeteer-fetch-html url')

let cookies
try {
    cookies = fs.readFileSync('fetch.txt').toString().split("\n")?.filter( v => /\s*"cookie":/.test(v))?.[0]?.split('"')?.filter(v => v.includes('='))[0]; //
} catch (_) { /* do nothing */ }

download(url, cookies)
